# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://:actioncable@pub-redis-16352.us-east-1-2.1.ec2.garantiadata.com:16352

development:
  adapter: redis
  url: redis://:actioncable@pub-redis-16352.us-east-1-2.1.ec2.garantiadata.com:16352

test:
  adapter: async